### ISSUE TITLE
fatal: unsafe repository

### ISSUE THREAD

**Issue by dertdog** [dertdog/external-repo-sync-action#1]
**Describe the bug**
When running the action in a workflow it will fail with `fatal: unsafe repository ('/tmp/tmp.######' is owned by someone else)`. I believe this may be a result of this updates for a [git-security-vulnerability](https://github.blog/2022-04-12-git-security-vulnerability-announced)

**To Reproduce**
Steps to reproduce
1. Run a github action with a workflow containing:
  ```
      - name: Upload coverage report to Wiki
        uses: kai-tub/external-repo-sync-action@v1
        with:
            source-directory: "./coveragereport"
            include-patterns: "*.md"
        env:
            GH_ACCESS_TOKEN: ${{ secrets.GH_WIKI_PAT }} 
  ```
2. This error occurs:
  ```
    Trying to infer wiki url of current repo
    Trying to infer user from $GITHUB_ACTOR
    Trying to infer default email from $GITHUB_ACTOR
    Using default commit message: Action Bot is pushing
    Using master branch by default
    Cloning into '.'...
    rsync -av --prune-empty-dirs --exclude=.git/ --include="*/" --include="*.md" --exclude="*" ./coveragereport/ /tmp/tmp.jeclBP
    building file list ... done
    ./
    Summary.md
    
    sent 2,8[32](https://github.com/tyler-technologies/ps-mobility-portal-common/runs/6031020301?check_suite_focus=true#step:12:32) bytes  received [38](https://github.com/tyler-technologies/ps-mobility-portal-common/runs/6031020301?check_suite_focus=true#step:12:38) bytes  5,7[40](https://github.com/tyler-technologies/ps-mobility-portal-common/runs/6031020301?check_suite_focus=true#step:12:40).00 bytes/sec
    total size is 2,711  speedup is 0.94
    fatal: unsafe repository ('/tmp/tmp.jeclBP' is owned by someone else)
    To add an exception for this directory, call:
    
	    git config --global --add safe.directory /tmp/tmp.jeclBP
    fatal: unsafe repository ('/tmp/tmp.jeclBP' is owned by someone else)
    To add an exception for this directory, call:
    
	    git config --global --add safe.directory /tmp/tmp.jeclBP
    fatal: unsafe repository ('/tmp/tmp.jeclBP' is owned by someone else)
    To add an exception for this directory, call:
    
	    git config --global --add safe.directory /tmp/tmp.jeclBP
    fatal: unsafe repository ('/tmp/tmp.jeclBP' is owned by someone else)
    To add an exception for this directory, call:
    
	    git config --global --add safe.directory /tmp/tmp.jeclBP
    Error: Error during pushing to git!
    Automatically deleting tmp dir
  ```
**Expected behavior**
The sync action succeeds.
